"""
Ticker lists for NSE Nifty 500 and NYSE large/mid-cap sample.
NSE tickers use .NS suffix (Yahoo Finance convention).
"""

# ── Nifty 500 representative list (top constituents + broad coverage) ──────────
NIFTY500_TICKERS = [
    # Large-cap heavyweights
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","ICICIBANK.NS","INFY.NS",
    "HINDUNILVR.NS","SBIN.NS","BHARTIARTL.NS","ITC.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "BAJFINANCE.NS","HCLTECH.NS","ULTRACEMCO.NS","TITAN.NS","WIPRO.NS",
    "NESTLEIND.NS","TECHM.NS","POWERGRID.NS","NTPC.NS","ONGC.NS",
    "JSWSTEEL.NS","TATAMOTORS.NS","TATASTEEL.NS","M&M.NS","ADANIENT.NS",
    "ADANIPORTS.NS","COALINDIA.NS","DIVISLAB.NS","DRREDDY.NS","CIPLA.NS",
    "BAJAJFINSV.NS","BPCL.NS","EICHERMOT.NS","HEROMOTOCO.NS","SHREECEM.NS",
    "BRITANNIA.NS","GRASIM.NS","APOLLOHOSP.NS","HINDALCO.NS","TATACONSUM.NS",
    "INDUSINDBK.NS","VEDL.NS","SBILIFE.NS","HDFCLIFE.NS","PIDILITIND.NS",
    # Mid-cap Nifty 500 names
    "MUTHOOTFIN.NS","CHOLAFIN.NS","PAGEIND.NS","BERGEPAINT.NS","ALKEM.NS",
    "LALPATHLAB.NS","METROPOLIS.NS","PERSISTENT.NS","COFORGE.NS","MPHASIS.NS",
    "LTIM.NS","LTTS.NS","OFSS.NS","KPITTECH.NS","ZOMATO.NS",
    "NYKAA.NS","POLICYBZR.NS","PAYTM.NS","IRCTC.NS","RVNL.NS",
    "RAILVIKAS.NS","IRFC.NS","PFC.NS","RECLTD.NS","HUDCO.NS",
    "NHPC.NS","SJVN.NS","CESC.NS","TORNTPOWER.NS","ADANIGREEN.NS",
    "ADANITRANS.NS","ADANIPOWER.NS","TATAPOWER.NS","SUZLON.NS","INOXWIND.NS",
    "MAZDOCK.NS","COCHINSHIP.NS","GRSE.NS","BEL.NS","HAL.NS",
    "BHEL.NS","BEML.NS","MIDHANI.NS","MFSL.NS","MAXHEALTH.NS",
    "FORTIS.NS","NARAYANA.NS","KIMS.NS","YATHARTH.NS","RAINBOW.NS",
    "GLAND.NS","LUPIN.NS","TORNTPHARM.NS","AUROPHARMA.NS","BIOCON.NS",
    "ABBOTINDIA.NS","PFIZER.NS","SANOFI.NS","GLAXO.NS","IPCALAB.NS",
    "NATCOPHARM.NS","GRANULES.NS","LAURUSLABS.NS","SUVEN.NS","DISHMAN.NS",
    "ALKYLAMINE.NS","AARTI.NS","DEEPAKNITR.NS","PIDILITIND.NS","SRF.NS",
    "FLUOROCHEM.NS","GALAXY.NS","VINATI.NS","FINEORG.NS","TATACHEM.NS",
    "GNFC.NS","GSFC.NS","CHAMBAL.NS","COROMANDEL.NS","UPL.NS",
    "PIIND.NS","BAYER.NS","RALLIS.NS","DHANUKA.NS","SUMITCHEM.NS",
    "ASTRAL.NS","SUPREMEIND.NS","FINOLEX.NS","VGUARD.NS","POLYCAB.NS",
    "KEI.NS","HAVELLS.NS","CROMPTON.NS","ORIENTELEC.NS","BAJAJELEC.NS",
    "VOLTAS.NS","BLUESTARCO.NS","AMBER.NS","DIXON.NS","KAYNES.NS",
    "SYRMA.NS","CYIENT.NS","TATAELXSI.NS","INFOEDGE.NS","JUSTDIAL.NS",
    "AFFLE.NS","INDIAMART.NS","CARTRADE.NS","EASEMYTRIP.NS","MAPMYINDIA.NS",
    "TANLA.NS","ROUTE.NS","INTELLECT.NS","MASTEK.NS","ZENSAR.NS",
    "HEXAWARE.NS","RATEGAIN.NS","NEWGEN.NS","NUCLEUS.NS","3MINDIA.NS",
    "HONAUT.NS","SIEMENS.NS","ABB.NS","CUMMINSIND.NS","THERMAX.NS",
    "BHARAT.NS","TIINDIA.NS","SCHAEFFLER.NS","SKFINDIA.NS","TIMKEN.NS",
    "GRINDWELL.NS","CARBORUNIV.NS","ATUL.NS","BASF.NS","TATAADVANCED.NS",
    "MOTHERSON.NS","BALKRISIND.NS","APOLLOTYRE.NS","MRF.NS","CEAT.NS",
    "EXIDEIND.NS","AMARAJABAT.NS","BOSCHLTD.NS","BHARATFORG.NS","ENDURANCE.NS",
    "SUNDRMFAST.NS","MAHINDCIE.NS","RAMKRISHNA.NS","RATNAMANI.NS","APL.NS",
    "SAREGAMA.NS","TIPS.NS","PVRINOX.NS","INOX.NS","EIDPARRY.NS",
    "BALRAMCHIN.NS","DWARIKESH.NS","TRIVENI.NS","RENUKA.NS","SHREECEM.NS",
    "JKCEMENT.NS","RAMCOCEM.NS","HEIDELBERG.NS","BIRLASOFT.NS","INDIACEM.NS",
    "DALMIA.NS","JKLAKSHMI.NS","STARC.NS","SUNTV.NS","NETWORK18.NS",
    "TV18BRDCST.NS","ZEEL.NS","SIEVERT.NS","NAUKRI.NS","MAKEMYTRIP.NS",
    "SHOPERSTOP.NS","TRENT.NS","VSTIND.NS","RADICO.NS","UNITDSPR.NS",
    "GMRINFRA.NS","CONCOR.NS","GATEWAY.NS","BLUEDART.NS","MAHLOG.NS",
    "GICRE.NS","NIACL.NS","STARHEALTH.NS","ICICIGI.NS","HDFCAMC.NS",
    "NIPPONLIFE.NS","ABSLAMC.NS","UTI.NS","360ONE.NS","ANGELONE.NS",
    "MOTILALOFS.NS","IIFL.NS","MANAPPURAM.NS","CANFINHOME.NS","REPCO.NS",
    "HOMEFIRST.NS","AAVAS.NS","APTUS.NS","SBFC.NS","FIVESTAR.NS",
    "UGROCAP.NS","CREDITACC.NS","SPANDANA.NS","FUSION.NS","ARMAN.NS",
    "EQUITASBNK.NS","SURYODAY.NS","ESAFSFB.NS","UJJIVAN.NS","JSFB.NS",
    "FEDERALBNK.NS","KARNATAKA.NS","SOUTHBNK.NS","DCBBANK.NS","RBLBANK.NS",
    "BANDHANBNK.NS","CSBBANK.NS","TMVFINANCE.NS","IDFCFIRSTB.NS","IDFC.NS",
    "BANKBARODA.NS","CANBK.NS","UNIONBANK.NS","INDIANB.NS","UCOBANK.NS",
    "CENTRALBK.NS","MAHABANK.NS","PSB.NS","BANKINDIA.NS","IOB.NS",
]

# ── NYSE representative large/mid-cap sample (~500 tickers) ───────────────────
NYSE_TICKERS = [
    # Tech
    "IBM","HPQ","HPE","ORCL","ACN","CSCO","DELL","NTAP","WDC","STX",
    "AMAT","LRCX","KLAC","TER","KEYS","GLW","CDW","NCR","JNPR","FFIV",
    # Financials
    "JPM","BAC","WFC","C","GS","MS","USB","PNC","TFC","COF",
    "AXP","BK","STT","SCHW","BLK","ICE","CME","CBOE","NDAQ","MCO",
    "SPGI","MET","PRU","AFL","ALL","TRV","CB","HIG","LNC","UNM",
    "AIG","PFG","VOYA","RGA","GL","FNF","FAF","SFG","EQH","PRI",
    # Healthcare
    "JNJ","PFE","MRK","ABT","MDT","UNH","CVS","HUM","CI","CNC",
    "MOH","ELV","HCA","THC","UHS","CYH","SEM","ENSG","AMED","CHE",
    "DVA","AHS","PRSC","ACHC","BKD","SHC","OPCH","LHCG","LFST","PNTG",
    "BMY","ABBV","LLY","AGN","WRK","BAX","BDX","BSX","EW","SYK",
    "ZBH","PHM","MTD","WAT","IQV","IQVIA","A","HOLX","IDXX","XRAY",
    # Energy
    "XOM","CVX","COP","SLB","HAL","BKR","MRO","OVV","DVN","FANG",
    "APA","EOG","HES","MPC","VLO","PSX","PBF","DK","PARR","CAPL",
    "KMI","WMB","OKE","ET","EPD","MMP","MPLX","PAA","TRGP","DT",
    # Industrials
    "GE","HON","MMM","CAT","DE","RTX","LMT","NOC","GD","BA",
    "TDG","HWM","SPR","KTOS","LDOS","SAIC","CACI","BAH","MANT","PSN",
    "UPS","FDX","XPO","CHRW","JBHT","KNX","WERN","SNDR","R","REXNORD",
    "EMR","ETN","PH","DOV","ITW","AME","ROK","SWK","GWW","MSC",
    # Consumer
    "WMT","TGT","HD","LOW","KR","SFM","WBA","CVS","RAD","COST",
    "DG","DLTR","BJ","FIVE","OLLI","TJX","ROST","BURL","GPS","PVH",
    "RL","HBI","PBI","KSS","JWN","M","DDS","SKX","NKE","UAA",
    "MCD","YUM","DPZ","CMG","DRI","TXRH","CAKE","BLMN","EAT","SG",
    "BUD","TAP","STZ","BF.B","MGPI","BEAM","WDFC","CLX","PG","KMB",
    "CHD","ENR","SPB","HRL","CAG","CPB","GIS","K","POST","SMPL",
    # Materials
    "LIN","APD","PPG","SHW","ECL","EMN","HUN","CC","ALB","FMC",
    "CF","MOS","NTR","IFF","RPM","AXTA","TROX","KRO","VNTR","HXL",
    "AA","NUE","STLD","RS","CMC","WOR","ZEUS","MTX","MLM","VMC",
    # Real estate
    "AMT","PLD","CCI","EQIX","SPG","O","AVB","EQR","ESS","MAA",
    "NNN","STOR","ADC","NTST","GTY","EPRT","BNL","FCPT","PINE","PECO",
    "PSA","EXR","CUBE","LSI","REXR","PRP","FR","EGP","LPT","STAG",
    "VTR","WELL","HR","NHI","OHI","SBRA","LTC","NHC","CTRE","NSHI",
    # Utilities
    "NEE","DUK","SO","D","EXC","AEP","XEL","ES","ETR","PPL",
    "FE","EIX","SRE","AEE","DTE","NI","CNP","CMS","WEC","LNT",
    "ATO","OGE","NWE","POR","AVA","IDACORP","HE","UIL","SWX","NTGR",
    # Telecom & Media
    "T","VZ","LUMN","SHEN","CNSL","LBTYA","CABO","WOW","ATUS","DISH",
    "FOX","FOXA","PARA","WBD","LGF.A","AMC","CNK","MCS","NUVEI","LAMR",
    "OUT","CCO","IHRT","SBGI","GTN","NCI","NXST","TVA","MGAM","BALY",
    # Autos / Transport
    "GM","F","TM","STLA","HOG","PII","THO","WGO","LCII","CWH",
    "R","AL","AIR","GATX","GBX","TRN","WAB","TT","GNSS","HLIO",
    # Banks & Regional
    "RF","KEY","HBAN","CFG","FITB","ZION","CMA","SNV","BOKF","WTFC",
    "PNFP","IBOC","CBSH","UMPQ","FFIN","INDB","NBT","WSBC","FULT","NBTB",
    # Misc / Diversified
    "BRK.B","MMC","AON","WTW","GEN","MKL","HCI","ERIE","RLI","KINGSWAY",
    "ITT","TDY","FTV","ROP","DHR","MIDD","NDSN","CSWI","NVT","ROPER",
]

MARKET_MAP = {
    "nse": NIFTY500_TICKERS,
    "nyse": NYSE_TICKERS,
}

def get_tickers(market: str) -> list[str]:
    return MARKET_MAP.get(market.lower(), [])
